//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXKIS.SmartWhere.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseColumnResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseColumnResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FXKIS.SmartWhere.Properties.Resources.DatabaseColumnResource", typeof(DatabaseColumnResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ALLOWED_DISK_IO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_AllowedDiskIO {
            get {
                return ResourceManager.GetString("GateEnvironment_AllowedDiskIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUFFER_SIZE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_BufferSize {
            get {
                return ResourceManager.GetString("GateEnvironment_BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CALCULATE_LPR_BYTE_SIZE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_CalculateLprByteSize {
            get {
                return ResourceManager.GetString("GateEnvironment_CalculateLprByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECTION_WAITING_TIMEOUT_MS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ConnectionWaitingTimeoutMS {
            get {
                return ResourceManager.GetString("GateEnvironment_ConnectionWaitingTimeoutMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_Date {
            get {
                return ResourceManager.GetString("GateEnvironment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FORCED_TERMINATED_TIMEOUT_MS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ForcedTerminatedTimeoutMS {
            get {
                return ResourceManager.GetString("GateEnvironment_ForcedTerminatedTimeoutMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ID {
            get {
                return ResourceManager.GetString("GateEnvironment_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IS_ENABLED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_IsEnabled {
            get {
                return ResourceManager.GetString("GateEnvironment_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IS_JOB_LOGGING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_IsJobLogging {
            get {
                return ResourceManager.GetString("GateEnvironment_IsJobLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG_MANAGING_CYCLE_MS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_LogManagingCycleMS {
            get {
                return ResourceManager.GetString("GateEnvironment_LogManagingCycleMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG_REMAIN_DAYS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_LogRemainDays {
            get {
                return ResourceManager.GetString("GateEnvironment_LogRemainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_Name {
            get {
                return ResourceManager.GetString("GateEnvironment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVICE_IP_ADDRESS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ServiceIPAddress {
            get {
                return ResourceManager.GetString("GateEnvironment_ServiceIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVICE_PORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ServicePort {
            get {
                return ResourceManager.GetString("GateEnvironment_ServicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMARTWHERE_IP_ADDRESS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_SmartWhereIPAddress {
            get {
                return ResourceManager.GetString("GateEnvironment_SmartWhereIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMARTWHERE_PORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_SmartWherePort {
            get {
                return ResourceManager.GetString("GateEnvironment_SmartWherePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEMP_SPOOL_DIRECTORY_PATH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_TempSpoolDirectoryPath {
            get {
                return ResourceManager.GetString("GateEnvironment_TempSpoolDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THREAD_MANAGING_CYCLE_MS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateEnvironment_ThreadManagingCycleMS {
            get {
                return ResourceManager.GetString("GateEnvironment_ThreadManagingCycleMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLIENT_ADDRESS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_ClientAddress {
            get {
                return ResourceManager.GetString("GateJobLog_ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLIENT_PORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_ClientPort {
            get {
                return ResourceManager.GetString("GateJobLog_ClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECTION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_Connection {
            get {
                return ResourceManager.GetString("GateJobLog_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_Date {
            get {
                return ResourceManager.GetString("GateJobLog_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DESCRIPTION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_Description {
            get {
                return ResourceManager.GetString("GateJobLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FILE_NAME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_FileName {
            get {
                return ResourceManager.GetString("GateJobLog_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_ID {
            get {
                return ResourceManager.GetString("GateJobLog_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IS_SUCCESS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_IsSuccess {
            get {
                return ResourceManager.GetString("GateJobLog_IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER_ADDRESS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_ServerAddress {
            get {
                return ResourceManager.GetString("GateJobLog_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVER_PORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GateJobLog_ServerPort {
            get {
                return ResourceManager.GetString("GateJobLog_ServerPort", resourceCulture);
            }
        }
    }
}
